fixtures:
    symlinks:
      knot: "#{source_dir}"
    repositories:
      stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
      concat: https://github.com/puppetlabs/puppetlabs-concat.git
      apt: https://github.com/puppetlabs/puppetlabs-apt.git
      tea: https://github.com/icann-dns/puppet-tea.git
