before_script:
  - who
  - pwd
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop