before_script:
  - whoami
  - touch test
  - ls -la test
  - rm test
  - pwd
  - ruby -v
  - which ruby
  - bundle install

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop